# Documentation: https://wiki.unvanquished.net/wiki/Continuous_integration

skip_branch_with_pr: true

only_commits:
  files:
    - .appveyor.yml
    # The rest of this list should stay in sync with azure-pipelines.yml
    - src/
    - libs/
    - cmake/
    - CMakeLists.txt
    - '*.cmake'
    - .gitmodules

branches:
  except:
    - debian

environment:
  matrix:
    # see 96d5c1f3ed77b09c64ce7c3c7cbd37c70456b3db
    # for NMake template
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: Visual Studio 16 2019
      platform: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: Visual Studio 16 2019
      platform: win32

build:
  parallel: true

before_build:
  - curl -sS https://gitlab.com/illwieckz/git-checkout-modules/raw/master/git-checkout-modules -o git-checkout-modules
  # The git-checkout-modules command below is normally equivalent to 'git submodule update --init --recursive',
  # but in the case that the branch name ends with '/sync' it tries to find branches with the same name.
  - bash git-checkout-modules
    --update
    --sub-ref=%APPVEYOR_REPO_BRANCH%:has=/sync$
    --sub-ref=%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%:has=/sync$
    --print

build_script:
  # simple line break: space
  # double line break: line break

  # There are two ways to do a multiprocessor build with CMake and MSVC,
  # the CMAKE_BUILD_PARALLEL_LEVEL variable instructs CMake to run
  # multiple tasks in parallel while the /MP compiler option instructs
  # the compiler to do multithreaded compilation. We already set /MP.
  # CMake reads CMAKE_BUILD_PARALLEL_LEVEL from environment.

  # The CFLAGS/CXXFLAGS env vars *prepend* to CMAKE_<lang>_FLAGS rather than overwriting.
  # /Wv pins warnings to a specific compiler version so that new ones
  # don't make the build error after Appveyor updates the compiler.

  - cmd: >

      echo %NUMBER_OF_PROCESSORS%

      set /a CMAKE_BUILD_PARALLEL_LEVEL="%NUMBER_OF_PROCESSORS% + 2"

      echo %CMAKE_BUILD_PARALLEL_LEVEL%

      cmake --version

      set CFLAGS=/Wv:19.29.30037

      set CXXFLAGS=/Wv:19.29.30037

      cmake
      -Wdev -Wdeprecated
      -G"%generator%" -A"%platform%"
      -DUSE_PRECOMPILED_HEADER=0 -DUSE_WERROR=1 -DBE_VERBOSE=1
      -DBUILD_DUMMY_APP=1 -DBUILD_TESTS=1
      -S. -Bbuild

      cmake --build build --config Release

      build\Release\test-dummyapp -pakpath pkg
